# Generated by Django 4.1 on 2022-09-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("viewflow", "0008_jsonfield_and_artifact"),
    ]

    operations = [
        migrations.CreateModel(
            name="HelloWorldProcess",
            fields=[],
            options={
                "verbose_name": "World Request",
                "verbose_name_plural": "World Requests",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("viewflow.process",),
        ),
    ]
