# Generated by Django 4.1 on 2022-08-31 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("viewflow", "0008_jsonfield_and_artifact"),
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HelloWorldProcess",
        ),
        migrations.CreateModel(
            name="HelloWorldProcess",
            fields=[],
            options={
                "verbose_name": "World Request",
                "verbose_name_plural": "World Requests",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("viewflow.process",),
        ),
    ]
